### ISSUE TITLE
0.0.5 has problems with particles at the boundaries.

### ISSUE THREAD

**Issue by BartBruininks** [BartBruininks/mdvwhole#21]
For now please use version 0.0.4

pip install mdvwhole==0.0.4

Do keep in mind that only cubic PBC is supported in this version.

**Comment by Tsjerk** [comment]
The problem appears to be that MDVoxelSegmentation assigns voxels to atoms (and vice versa) for voxels in the most bricklike representation of the unit cell, but does not change the particle positions accordingly. Therefore, these retain their out-of-the-voxel positions and at the point where atoms are to be shifted they are shifted with respect to their real coordinates and not the in-voxel coordinates they should have. This can/should be fixed by having MDVS change the positions of the particles. The fix is already done, but remains to be tested. It may give a slight performance hit on MDVS clustering, because of additional operations (moving particles). A fix in mdvwhole would probably become too clunky.

**Comment by BartBruininks** [comment]
I wonder if this is indeed the issue. Why would this problem not pop up in the earlier 0.0.4 and why does it also pop up for frames which already lie completely in the frame (xtc frames)?

**Comment by BartBruininks** [comment]
I see now. Feel free to make the suggested change to MDVS, I agree that it becomes cluncky if we force it here. If you implement it, I will test it against the complex systems.

**Comment by BartBruininks** [comment]
Did you try with the dipeptides if this solves the issue? For me it doesn't seem to fix it, but maybe I am not updating my MDVS correctly.
